["âš™ï¸ Enhancement"]
color = "C2E0C6"
name = "âš™ï¸ Enhancement"
description = "Improvements and optimizations of existing features"

["âš ï¸ Interface"]
color = "F9D0C4"
name = "âš ï¸ Interface"
description = "Breaking changes to the API"

["âšª Duplicate"]
color = "CFD3D7"
name = "âšª Duplicate"
description = "This issue or pull request already exists"

["âœ¨ Feature"]
color = "C2E0C6"
name = "âœ¨ Feature"
description = "New feature added to the package"

["â” Question"]
color = "88506B"
name = "â” Question"
description = "Discuss this matter in the team"

["â— Behavior"]
color = "F9D0C4"
name = "â— Behavior"
description = "Changes that may affect the framework output"

["ğŸ› Bug"]
color = "D93F0B"
name = "ğŸ› Bug"
description = "Something isn't working"

["ğŸ’¥ Epic"]
color = "3E4B9E"
name = "ğŸ’¥ Epic"
description = "Collection of issues"

["ğŸ’« Good first issue"]
color = "F4EAEF"
name = "ğŸ’« Good first issue"
description = "Good for newcomers"

["ğŸ’¬ Meeting"]
color = "BFD4F2"
name = "ğŸ’¬ Meeting"
description = "Weekly PWA working group meeting"

["ğŸ“‹ Task"]
color = "1D76DB"
name = "ğŸ“‹ Task"
description = "Task for the to-do list"

["ğŸ“– Analysis"]
color = "FBE2BD"
name = "ğŸ“– Analysis"
description = "About HEP analysis techniques"

["ğŸ“– Software"]
color = "FDF3E4"
name = "ğŸ“– Software"
description = "About software development"

["ğŸ“– Theory"]
color = "F7C57B"
name = "ğŸ“– Theory"
description = "About PWA theory"

["ğŸ“ Docs"]
color = "BFD4F2"
name = "ğŸ“ Docs"
description = "Improvements or additions to documentation"

["ğŸ”¨ Maintenance"]
color = "FFCD8F"
name = "ğŸ”¨ Maintenance"
description = "Maintenance and upkeep improvements"

["ğŸ–±ï¸ DX"]
color = "FEF2C0"
name = "ğŸ–±ï¸ DX"
description = "Improvements to the Developer Experience"
